// Essential Lucide React icons for the expense splitter app
export {
  // Core navigation and UI
  Receipt,
  CreditCard,
  Users,
  User,
  Activity,
  LogOut,
  Plus,
  Minus,
  Edit,
  Trash2,
  Check,
  X,
  Save,
  DollarSign,
  Calendar,
  Search,
  Filter,
  Settings,
  Home,
  PieChart,
  TrendingUp,
  TrendingDown,
  AlertCircle,
  Info,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Mail,
  Phone,
  MapPin,
  Clock,
  Star,
  Heart,
  Share,
  Download,
  Upload,
  RefreshCw,
  RotateCcw,
  Power,
  Shield,
  Zap,
  Target,
  Award,
  Gift,
  ShoppingCart,
  Package,
  Truck,
  Store,
  Building,
  Briefcase,
  GraduationCap,
  BookOpen,
  FileText,
  Image,
  Video,
  Music,
  Camera,
  Mic,
  Headphones,
  Gamepad2,
  Palette,
  Brush,
  Scissors,
  Wrench,
  Hammer,
  Cog,
  Bell,
  BellOff,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Smartphone,
  Tablet,
  Monitor,
  Laptop,
  Server,
  Database,
  Cloud,
  CloudOff,
  Globe,
  Map,
  Navigation,
  Compass,
  Flag,
  Anchor,
  Ship,
  Plane,
  Car,
  Bike,
  Bus,
  Rocket,
  Satellite,
  Telescope,
  Microscope,
  Pill,
  Stethoscope,
  Brain,
  Bone,
  Fingerprint,
  ThumbsUp,
  ThumbsDown,
  Frown,
  Smile,
  Meh,
  Laugh,
  Angry,
  Cross,
  Moon,
  Sun,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Umbrella,
  Snowflake,
  Droplets,
  Thermometer,
  Gauge,
  BarChart3,
  LineChart,
  Trophy,
  Medal,
  Crown,
  Gem,
  Diamond,
  Sparkles,
  Flame,
  Leaf,
  Trees,
  Flower,
  Sprout,
  Bug,
  Fish,
  Bird,
  Cat,
  Dog,
  // Finance and business icons
  CreditCard as Card,
  DollarSign as Money,
  Receipt as Bill,
  PieChart as Chart,
  TrendingUp as UpTrend,
  TrendingDown as DownTrend,
  BarChart3 as BarChart,
  LineChart as LineChartIcon,
  // User and profile icons
  User as Profile,
  Users as Group,
  UserCheck,
  UserPlus,
  UserMinus,
  UserX,
  // Action icons
  Plus as Add,
  Minus as Remove,
  Edit as EditIcon,
  Trash2 as Delete,
  Check as CheckIcon,
  X as Close,
  Save as SaveIcon,
  // Navigation icons
  Home as HomeIcon,
  Settings as SettingsIcon,
  Search as SearchIcon,
  Filter as FilterIcon,
  // Status icons
  AlertCircle as Alert,
  Info as InfoIcon,
  CheckCircle,
  XCircle,
  AlertTriangle,
  // Direction icons
  ChevronDown as Down,
  ChevronUp as Up,
  ChevronLeft as Left,
  ChevronRight as Right,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  // Media icons
  Image as ImageIcon,
  Video as VideoIcon,
  Music as MusicIcon,
  Camera as CameraIcon,
  Mic as MicIcon,
  Headphones as HeadphonesIcon,
  // Technology icons
  Smartphone as PhoneIcon,
  Tablet as TabletIcon,
  Monitor as MonitorIcon,
  Laptop as LaptopIcon,
  Server as ServerIcon,
  Database as DatabaseIcon,
  Cloud as CloudIcon,
  Wifi as WifiIcon,
  // Time and date icons
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  // Communication icons
  Mail as MailIcon,
  Phone as PhoneIcon,
  MessageSquare,
  MessageCircle,
  // Location icons
  MapPin as Location,
  Map as MapIcon,
  Navigation as NavigationIcon,
  Compass as CompassIcon,
  // Weather icons
  Sun as SunIcon,
  Moon as MoonIcon,
  Cloud as CloudIcon,
  CloudRain as Rain,
  CloudSnow as Snow,
  CloudLightning as Lightning,
  Wind as WindIcon,
  // Nature icons
  Leaf as LeafIcon,
  Trees as TreeIcon,
  Flower as FlowerIcon,
  Sprout as SproutIcon,
  Bug as BugIcon,
  Fish as FishIcon,
  Bird as BirdIcon,
  Cat as CatIcon,
  Dog as DogIcon,
  // Emotion icons
  Smile as SmileIcon,
  Frown as FrownIcon,
  Meh as MehIcon,
  Laugh as LaughIcon,
  Angry as AngryIcon,
  // Action icons
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Power as PowerIcon,
  Shield as ShieldIcon,
  Zap as ZapIcon,
  Target as TargetIcon,
  Award as AwardIcon,
  Gift as GiftIcon,
  ShoppingCart as Cart,
  Package as PackageIcon,
  Truck as TruckIcon,
  Store as StoreIcon,
  Building as BuildingIcon,
  Briefcase as BriefcaseIcon,
  GraduationCap as Graduation,
  BookOpen as Book,
  FileText as File,
  Gamepad2 as Gamepad,
  Palette as PaletteIcon,
  Brush as BrushIcon,
  Scissors as ScissorsIcon,
  Wrench as WrenchIcon,
  Hammer as HammerIcon,
  Cog as CogIcon,
  Bell as BellIcon,
  BellOff as BellOffIcon,
  Volume2 as Volume,
  VolumeX as VolumeOff,
  Battery as BatteryIcon,
  BatteryCharging as Charging,
  Rocket as RocketIcon,
  Satellite as SatelliteIcon,
  Telescope as TelescopeIcon,
  Microscope as MicroscopeIcon,
  Pill as PillIcon,
  Stethoscope as StethoscopeIcon,
  Brain as BrainIcon,
  Bone as BoneIcon,
  Fingerprint as FingerprintIcon,
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown as ThumbsDownIcon,
  Cross as CrossIcon,
  Umbrella as UmbrellaIcon,
  Snowflake as SnowflakeIcon,
  Droplets as DropletsIcon,
  Thermometer as ThermometerIcon,
  Gauge as GaugeIcon,
  Trophy as TrophyIcon,
  Medal as MedalIcon,
  Crown as CrownIcon,
  Gem as GemIcon,
  Diamond as DiamondIcon,
  Sparkles as SparklesIcon,
  Flame as FlameIcon,
  // Social icons
  Share as ShareIcon,
  Heart as HeartIcon,
  Star as StarIcon,
  // Utility icons
  Download as DownloadIcon,
  Upload as UploadIcon,
  RefreshCw as Refresh,
  RotateCcw as Rotate,
  MoreHorizontal as More,
} from "lucide-react";
